### ISSUE TITLE
Typo in orphan page: http://learn.github.com/p/tagging.html

### ISSUE THREAD

**Issue by dorentus** [github/learn.github.com#36]
Found this page by Google searching `git show signature github`. It took a while before I realized that this page is not maintained anymore.

However, there's a typo in the generated HTML (the **sharing tags** section): the text `–tags`, or `&#8211;tags`, should be `--tags`.

It would be nice if you guys fix it, or, just delete that page.

**Comment by matthewmccullough** [comment]
Hey @randomecho – Since you've hacked a bit on this, is there an easy fix in the generator?  Source?  Calling all @brntbeer for a sidecar fix too. :smile:

**Comment by randomecho** [comment]
The tagging page was dropped from the episode list in 241a3865e4348900acaa975d3af3f7fe85f3bce1

Guess you could then update the Rakefile to just delete everything in **p** every time you run it in order to only have currently listed lessons and a clean slate, leaving 404s for anything no longer listed in the episodes.

**Comment by brntbeer** [comment]
This should be closed since the most recent change to Jekyllifying this site
